Add camera-streaming-daemon package
intel-aero/packages pull request #2
Opened 2017-11-09 13:21 UTC by Rjasuja

Enable Camera streaming daemon

2017-11-09 13:23 UTC, Rjasuja commented
Installed librealsense(legacy branch for RS200) alongwith this package. Camera streaming daemon service launched successfully. Tested streaming using gstreamer pipelines as well

2017-11-09 13:41 UTC, anitha-suresh commented
Link to download librealsense legacy branch: https://github.com/IntelRealSense/librealsense/tree/legacy

2017-11-10 09:56 UTC, avinash-palleti approved these changes

2017-11-16 01:28 UTC, anselmolsm requested changes

2017-11-16 01:28 UTC, anselmolsm commented on aero-camera-streaming-daemon/aero-camera-streaming-daemon_1.0/debian/control
> +Depends: ${shlibs:Depends}, ${misc:Depends}, python-future
Move python-future to Build-Depends

2017-11-16 01:28 UTC, anselmolsm commented on aero-camera-streaming-daemon/aero-camera-streaming-daemon_1.0/debian/control
> +Standards-Version: 3.9.6
See lintian output in the end of the package build.

2017-11-16 01:28 UTC, anselmolsm commented on aero-camera-streaming-daemon/aero-camera-streaming-daemon_1.0/debian/changelog
> +camera-streaming-daemon (1.0-1) unstable; urgency=medium
unstable -> xenial

2017-11-16 01:28 UTC, anselmolsm commented on aero-camera-streaming-daemon/aero-camera-streaming-daemon_1.0/debian/copyright
> +
Add:
```
 /usr/share/common-licenses/Apache-2.0
```

2017-11-16 01:28 UTC, anselmolsm commented on aero-camera-streaming-daemon/aero-camera-streaming-daemon_1.0/debian/copyright
> +License: Apache-2.0
Add:
```
 /usr/share/common-licenses/Apache-2.0
```

2017-11-16 01:28 UTC, anselmolsm commented on aero-camera-streaming-daemon/aero-camera-streaming-daemon_1.0/debian/aero-camera-streaming-daemon.install
> +config/csd etc/init.d
Shouldn't be a systemd service?

2017-11-16 01:29 UTC, anselmolsm commented
Also, please rebase

2017-11-17 23:27 UTC, merged

2017-11-18 01:24 UTC, anselmolsm commented
Reverted. Please resubmit.

2017-12-15 00:57 UTC, anselmolsm commented on aero-camera-streaming-daemon/aero-camera-streaming-daemon_1.0/debian/control
> +Priority: optional
**Section** field is missing