Add aero-sample-apps package
intel-aero/packages pull request #29
Opened 2017-12-15 09:58 UTC by avinash-palleti

Adding aero-sample-apps package which depends on ros-sample-apps

2017-12-15 10:05 UTC, anitha-suresh commented on aero-sample-apps/aero-sample-apps
> +Priority: important
I think priority can be 'optional'

2017-12-15 10:05 UTC, anitha-suresh commented on aero-sample-apps/aero-sample-apps
> +Description: Collection of Sample applications to run on Aero.
"Sample applications to run on Aero" -> Sample applications can be run on Aero

2017-12-15 10:10 UTC, anitha-suresh commented on aero-sample-apps/aero-sample-apps
> +Section: misc
This indicates that Debian package is stored at the 'misc' folder in the site where we are hosting the package. We need to re-check on this.

2017-12-15 10:26 UTC, anitha-suresh commented on aero-sample-apps/aero-sample-apps
> +Description: Collection of Sample applications can be run on Aero.
Collection of Sample applications *that* can be run on Aero.

2017-12-19 23:34 UTC, anselmolsm commented
IMO this meta package should be added with / after the packages it installs

2017-12-21 22:06 UTC, anselmolsm requested changes
Add a note in the commit indicating these packages take care of their own packaging (i.e. they deal with the debian dir magic)

2017-12-22 03:26 UTC, avinash-palleti commented
@anselmolsm Done.

2018-01-03 08:00 UTC, anitha-suresh-zz reviewed
Spell check : avialble

2018-01-11 06:06 UTC, merged